version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.0.4
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kowl:
    image: quay.io/cloudhut/kowl:v1.5.0
    restart: on-failure
    volumes:
      - ./kowl/config.yaml:/etc/kowl/config.yaml
    ports:
      - "127.0.0.1:9003:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - broker

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.0.4
    depends_on:
      - broker
    ports:
      - 9001:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      ZIPKIN_HTTP_PORT: 9411
      # Optional: You can configure the storage type if needed
      # ZIPKIN_STORE_TYPE: "mysql" # For example, if you want to use MySQL for storage
      # Additional configurations for storage, sampling, etc., can be added here

networks:
  default:
    name: kafka-network
