spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      default-topic: my-topic
    listener:
      observation-enabled: true
    template:
      observation-enabled: true

  application:
    name: tracing-consumer
  reactor:
    context-propagation: auto
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
#    baggage:
#      enabled: true
#      correlation:
#        enabled: true
#    propagation:
#      consume: b3, b3_multi, w3c
#      type: b3, w3c, b3_multi
#      produce: b3, b3_multi, w3c
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    annotations:
      enabled: true
logging:
  level:
    org.springframework.kafka: DEBUG
    reactor.kafka: DEBUG
    io.micrometer.observation: DEBUG

